import 'dotenv/config';
import {createHmac,randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
const arg=name=>{const i=process.argv.indexOf(name);return i>=0?process.argv[i+1]:undefined};
const body=arg('--file')?await readFile(arg('--file'),'utf8'):JSON.stringify({eventId:arg('--event-id')||randomUUID(),externalLeadId:arg('--lead-id')||'demo-'+randomUUID(),version:Number(arg('--version')||1),occurredAt:new Date().toISOString(),data:{fullName:arg('--name')||'Aarav Mehta',email:'aarav@example.test',phone:'+919876543210',company:'Orbit Labs',campaign:'Founder community'}});
const timestamp=String(Math.floor(Date.now()/1000));
const secret=process.env.WEBHOOK_SECRET||'local-webhook-secret-change-before-deploy-123';
const signature='sha256='+createHmac('sha256',secret).update(timestamp+'.').update(body).digest('hex');
const response=await fetch((process.env.API_URL||'http://localhost:3000')+'/webhook/meta-lead',{method:'POST',headers:{'Content-Type':'application/json','X-Webhook-Key-Id':process.env.WEBHOOK_KEY_ID||'local-meta','X-Webhook-Timestamp':timestamp,'X-Webhook-Signature':signature},body});
console.log(response.status,await response.text());
if(!response.ok)process.exitCode=1;
